### ISSUE TITLE
vg simplify: exon positions of different tracks from bed file seem not to match

### ISSUE THREAD

**Issue by wolfib** [adamnovak/vg#1]
While drawing graphs for Notch2 I discovered that there seems to be a mismatch between the exon starting positions of different tracks from the same graph.

Here are two lines from simplified-5000.bed:
```
Notch2	        18036	18189	exon1
Notch2NLA	19376	19522	exon1
```

The exon lies within the node with id 11423. Adding up the path lengths for Notch2 and Notch2NLA until node 11423, I get 17423 and 17405 respectively. This means that, within node 11423,  the exon starts at position 613 for Notch2 and at position 1971 for Notch2NLA. Shouldn't they start at the same position?

It's absolutely possible that there's something wrong with my calculation. Here are the relevant parts of simplified-5000.json:

`"path": [{"name": "Notch2", "mapping": [{"position": {"node_id": 11378}, "rank": 1, "edit": [{"from_length": 1725, "to_length": 1725}]}, {"position": {"node_id": 55}, "rank": 2, "edit": [{"from_length": 2, "to_length": 2}]}, {"position": {"node_id": 11379}, "rank": 3, "edit": [{"from_length": 19, "to_length": 19}]}, {"position": {"node_id": 11382}, "rank": 4, "edit": [{"from_length": 4653, "to_length": 4653}]}, {"position": {"node_id": 11383}, "rank": 5, "edit": [{"from_length": 58, "to_length": 58}]}, {"position": {"node_id": 727}, "rank": 6, "edit": [{"from_length": 3, "to_length": 3}]}, {"position": {"node_id": 11384}, "rank": 7, "edit": [{"from_length": 58, "to_length": 58}]}, {"position": {"node_id": 11387}, "rank": 8, "edit": [{"from_length": 1349, "to_length": 1349}]}, {"position": {"node_id": 11388}, "rank": 9, "edit": [{"from_length": 128, "to_length": 128}]}, {"position": {"node_id": 11389}, "rank": 10, "edit": [{"from_length": 898, "to_length": 898}]}, {"position": {"node_id": 956}, "rank": 11, "edit": [{"from_length": 4, "to_length": 4}]}, {"position": {"node_id": 11391}, "rank": 12, "edit": [{"from_length": 58, "to_length": 58}]}, {"position": {"node_id": 11393}, "rank": 13, "edit": [{"from_length": 11, "to_length": 11}]}, {"position": {"node_id": 11395}, "rank": 14, "edit": [{"from_length": 4588, "to_length": 4588}]}, {"position": {"node_id": 1778}, "rank": 15, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 11396}, "rank": 16, "edit": [{"from_length": 389, "to_length": 389}]}, {"position": {"node_id": 11397}, "rank": 17, "edit": [{"from_length": 402, "to_length": 402}]}, {"position": {"node_id": 11402}, "rank": 18, "edit": [{"from_length": 104, "to_length": 104}]}, {"position": {"node_id": 11403}, "rank": 19, "edit": [{"from_length": 24, "to_length": 24}]}, {"position": {"node_id": 11404}, "rank": 20, "edit": [{"from_length": 239, "to_length": 239}]}, {"position": {"node_id": 11405}, "rank": 21, "edit": [{"from_length": 18, "to_length": 18}]}, {"position": {"node_id": 11407}, "rank": 22, "edit": [{"from_length": 103, "to_length": 103}]}, {"position": {"node_id": 1962}, "rank": 23, "edit": [{"from_length": 2, "to_length": 2}]}, {"position": {"node_id": 1963}, "rank": 24, "edit": [{"from_length": 5, "to_length": 5}]}, {"position": {"node_id": 11408}, "rank": 25, "edit": [{"from_length": 18, "to_length": 18}]}, {"position": {"node_id": 11412}, "rank": 26, "edit": [{"from_length": 2427, "to_length": 2427}]}, {"position": {"node_id": 11418}, "rank": 27, "edit": [{"from_length": 106, "to_length": 106}]}, {"position": {"node_id": 11421}, "rank": 28, "edit": [{"from_length": 18, "to_length": 18}]}, {"position": {"node_id": 2306}, "rank": 29, "edit": [{"from_length": 13, "to_length": 13}]}, {"position": {"node_id": 11423}, "rank": 30, "edit": [{"from_length": 12890, "to_length": 12890}]},...`

`
{"name": "Notch2NLA", "mapping": [{"position": {"node_id": 11380}, "rank": 1, "edit": [{"from_length": 1728, "to_length": 1728}]}, {"position": {"node_id": 11379}, "rank": 2, "edit": [{"from_length": 19, "to_length": 19}]}, {"position": {"node_id": 11382}, "rank": 3, "edit": [{"from_length": 4653, "to_length": 4653}]}, {"position": {"node_id": 11383}, "rank": 4, "edit": [{"from_length": 58, "to_length": 58}]}, {"position": {"node_id": 727}, "rank": 5, "edit": [{"from_length": 3, "to_length": 3}]}, {"position": {"node_id": 11385}, "rank": 6, "edit": [{"from_length": 1408, "to_length": 1408}]}, {"position": {"node_id": 11388}, "rank": 7, "edit": [{"from_length": 128, "to_length": 128}]}, {"position": {"node_id": 11390}, "rank": 8, "edit": [{"from_length": 896, "to_length": 896}]}, {"position": {"node_id": 11391}, "rank": 9, "edit": [{"from_length": 58, "to_length": 58}]}, {"position": {"node_id": 11393}, "rank": 10, "edit": [{"from_length": 11, "to_length": 11}]}, {"position": {"node_id": 11395}, "rank": 11, "edit": [{"from_length": 4588, "to_length": 4588}]}, {"position": {"node_id": 1778}, "rank": 12, "edit": [{"from_length": 1, "to_length": 1}]}, {"position": {"node_id": 11396}, "rank": 13, "edit": [{"from_length": 389, "to_length": 389}]}, {"position": {"node_id": 11398}, "rank": 14, "edit": [{"from_length": 763, "to_length": 763}]}, {"position": {"node_id": 1871}, "rank": 15, "edit": [{"from_length": 5, "to_length": 5}]}, {"position": {"node_id": 11405}, "rank": 16, "edit": [{"from_length": 18, "to_length": 18}]}, {"position": {"node_id": 11407}, "rank": 17, "edit": [{"from_length": 103, "to_length": 103}]}, {"position": {"node_id": 1962}, "rank": 18, "edit": [{"from_length": 2, "to_length": 2}]}, {"position": {"node_id": 1963}, "rank": 19, "edit": [{"from_length": 5, "to_length": 5}]}, {"position": {"node_id": 11409}, "rank": 20, "edit": [{"from_length": 757, "to_length": 757}]}, {"position": {"node_id": 2136}, "rank": 21, "edit": [{"from_length": 7, "to_length": 7}]}, {"position": {"node_id": 11415}, "rank": 22, "edit": [{"from_length": 20, "to_length": 20}]}, {"position": {"node_id": 11416}, "rank": 23, "edit": [{"from_length": 101, "to_length": 101}]}, {"position": {"node_id": 2146}, "rank": 24, "edit": [{"from_length": 7, "to_length": 7}]}, {"position": {"node_id": 11417}, "rank": 25, "edit": [{"from_length": 1540, "to_length": 1540}]}, {"position": {"node_id": 11418}, "rank": 26, "edit": [{"from_length": 106, "to_length": 106}]}, {"position": {"node_id": 11421}, "rank": 27, "edit": [{"from_length": 18, "to_length": 18}]}, {"position": {"node_id": 2306}, "rank": 28, "edit": [{"from_length": 13, "to_length": 13}]}, {"position": {"node_id": 11423}, "rank": 29, "edit": [{"from_length": 12890, "to_length": 12890}]},...
`

**Comment by adamnovak** [comment]
I'm going to close this; please re-open it on the main vg repo if it's still a problem.
